### ISSUE TITLE
Security fixes in nBox

### ISSUE THREAD

**Issue by lucaderi** [javuto/nbox-pwnage#1]
Hello, I have been informed of this project by a friend. I am part of the ntop team and I personally was not aware of these issues as described in http://carnal0wnage.attackresearch.com/2016/08/got-any-rces.html?m=1. If you have a security concern you can report this to us as described here http://www.ntop.org/support/misc/security/.
This said I have made some quick patches and the issues you reported have been fixes. In the coming days we'll go over the code and complete the work.

Thank you.

**Comment by javuto** [comment]
@lucaderi, thank you for reaching out. I am glad the reported issues have been fixed. Is there any plan to notify the current nbox recorder users about this problems? My goal making this public post was to be able to make the issues visible, instead of just issue a patch.
Anyway, I am happy to verify the patch. Although you can use this tool for that purpose.
Thanks!

**Comment by lucaderi** [comment]
Javier like I have said tonight I have put some patches just to immediately address the issues.p, but more work to clean up the code is necessary. Unfortunately the nbox is old code that need some rework, and due to our laziness (whiz open source)  it is not yet sitting on github, where adding patches is easy and contributions too: this is our next priority. Feel free to update your users about the patches we introduced. Thank you again for reporting the issues.

**Comment by javuto** [comment]
@lucaderi the point is not to just fix the code. Releasing a note to say that you have fixed critical vulnerabilities would be a better approach. That is the point of CVEs or release notes. You should care about who uses **YOUR** product. 
At this point, your code is only good to be used for CTF challenges. And not even for high points.

**Comment by lucaderi** [comment]
The nBox is not my code, is written by ntop but I am not the author. This however is not the point. We care about security and I have patched the code within 2h since I have been aware of it. In the future, please make sure to contact us using http://www.ntop.org/support/misc/security/ or send me a direct email. Finally if you have code patches to share, please feel free to do: I think they are much more valuable. Later this summer we'll put the code on github so that this process will be easier. Thanks again for reporting the issues, and thus make nBox better.
